frontend/controllers/AncController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Anc;
use frontend\models\AncSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AncController implements the CRUD actions for Anc model.
 */
class AncController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Anc models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AncSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Anc model.
     * @param string $HOSPCODE
     * @param string $PID
     * @param string $DATE_SERV
     * @return mixed
     */
    public function actionView($HOSPCODE, $PID, $DATE_SERV)
    {
        return $this->render('view', [
            'model' => $this->findModel($HOSPCODE, $PID, $DATE_SERV),
        ]);
    }

    /**
     * Creates a new Anc model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Anc();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'HOSPCODE' => $model->HOSPCODE, 'PID' => $model->PID, 'DATE_SERV' => $model->DATE_SERV]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Anc model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $HOSPCODE
     * @param string $PID
     * @param string $DATE_SERV
     * @return mixed
     */
    public function actionUpdate($HOSPCODE, $PID, $DATE_SERV)
    {
        $model = $this->findModel($HOSPCODE, $PID, $DATE_SERV);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'HOSPCODE' => $model->HOSPCODE, 'PID' => $model->PID, 'DATE_SERV' => $model->DATE_SERV]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Anc model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $HOSPCODE
     * @param string $PID
     * @param string $DATE_SERV
     * @return mixed
     */
    public function actionDelete($HOSPCODE, $PID, $DATE_SERV)
    {
        $this->findModel($HOSPCODE, $PID, $DATE_SERV)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Anc model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $HOSPCODE
     * @param string $PID
     * @param string $DATE_SERV
     * @return Anc the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($HOSPCODE, $PID, $DATE_SERV)
    {
        if (($model = Anc::findOne(['HOSPCODE' => $HOSPCODE, 'PID' => $PID, 'DATE_SERV' => $DATE_SERV])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/ReportController.php
<?php

namespace frontend\controllers;

use yii;
use kartik\grid\GridView;

class ReportController extends \yii\web\Controller {

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionReport1() {
        $sql = "SELECT HOSPCODE as 'หน่วยบริการ',DATE_SERV as 'วันที่บริการ',ANCPLACE as 'สถานที่คลอด' from anc
WHERE DATE_SERV >'2014-10-1' and ANCPLACE is not NULL  ";
        //$rawData = \yii::$app->db->createCommand($sql)->queryAll();
        //print_r($rawData);
        try {
            $rawData = \yii::$app->db->createCommand($sql)->queryAll();
        } catch (\yii\db\Exception $e) {
            throw new \yii\web\ConflictHttpException('sql error');
        }
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $rawData,
            'pagination'=>[
                'pagesize'=>25]
        ]);

        return $this->render('report1', [
                    'dataProvider' => $dataProvider
        ]);
    }

}

frontend/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => 'KPI_QOF',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            //การเพิ่มเมนู dropdown ขัั้นที่ 1
            $report_mnu_itms[] = ['label' => 'MCH', 'url' => ['report/index']];
            $report_mnu_itms[] = ['label' => 'NUTRITION', 'url' => ['anc/index']];

            $menuItems = [
                ['label' => 'Home', 'url' => ['/site/index']],
                //การเพิ่มเมนู dropdown ขัั้นที่ 2    
                ['label' => 'Report',
                    'items' => $report_mnu_itms],
                ['label' => 'Contact', 'url' => ['/site/contact']],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>
<?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy; งานข้อมูล  กลุ่มงานพัฒนายุทธศาสตร์สาธารณสุข <?= date('Y') ?></p>

                <p class="pull-right"><?= Yii::powered() ?></p>
            </div>
        </footer>

<?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>